export const PageRoutes = {
  DASHBOARD: '/dashboard',
  COUNTRIES: '/dashboard/administrative/countries',
  ADMINS: '/dashboard/administrative/administrators',
  USERS: '/dashboard/main/users',
  PARTNERS: '/dashboard/main/partners',
  OUTLETS: '/dashboard/main/outlets',
  PHUBERS: '/dashboard/main/phubers',
  MENU: '/dashboard/main/menu',
  PROMO: '/dashboard/main/promo',
  LOYALTY: '/dashboard/main/loyalty',
  ORDERS: '/dashboard/main/orders',
  GOD_VIEW: '/dashboard/main/god-view',
  CATEGORIES: '/dashboard/main/categories',
  NOTIFICATIONS: '/dashboard/extras/notifications',
  ALERTS: '/dashboard/extras/alerts',
  CHATS: '/dashboard/extras/chats',
  PROFILE: '/dashboard/extras/profile',
  SETTINGS: '/dashboard/extras/settings',
};
